typography_spectrum: 0.3860977420117706
color:
  brandColors:
    - '#171612'
    - '#dddad2'
    - '#656157'
    - '#0081ce'
    - '#05418b'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
opengraph: {}
layout_spectrum: 1
analytics: {}
author:
  name: Gabe Gibitz
  email: gibitzga@gmail.com
  url: gabegibitz.com
name: Gabe Gibitz
cta: {}
title: Worship Leader. Psalmist. Revivalist.
purpose: []
