name: Gabe Gibitz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3860977420117706
title: Gabe Gibitz - Worship Leader. Psalmist. Revivalist.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171612'
    - '#dddad2'
    - '#656157'
    - '#0081ce'
    - '#05418b'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
