analytics: {}
color:
  brandColors:
    - '#171612'
    - '#dddad2'
    - '#656157'
    - '#0081ce'
    - '#05418b'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 1
name: Gabe Gibitz
opengraph: {}
purpose: []
typography_spectrum: 0.3860977420117706
